//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasSSyPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public Almacen()
        {
            this.Tbl_Inventario = new HashSet<Tbl_Inventario>();
        }
    
        public int id_Almacen { get; set; }
        public int id_Corporacion { get; set; }
        public int id_Usuario { get; set; }
        public string Nombre { get; set; }
    
        public virtual Corporacion Corporacion { get; set; }
        public virtual ICollection<Tbl_Inventario> Tbl_Inventario { get; set; }
    }
}
