//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasSSyPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Producto
    {
        public Cat_Producto()
        {
            this.Ingredientes = new HashSet<Ingredientes>();
            this.Tbl_Inventario = new HashSet<Tbl_Inventario>();
        }
    
        public int id_Producto { get; set; }
        public int id_UnidadesdeMedida { get; set; }
        public int id_Marca { get; set; }
        public int id_Modelo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public byte[] Activo { get; set; }
    
        public virtual Cat_Marca Cat_Marca { get; set; }
        public virtual Cat_Modelo Cat_Modelo { get; set; }
        public virtual Unidades_de__medida Unidades_de__medida { get; set; }
        public virtual ICollection<Ingredientes> Ingredientes { get; set; }
        public virtual ICollection<Tbl_Inventario> Tbl_Inventario { get; set; }
    }
}
