//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasSSyPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes
    {
        public Nullable<int> FK_Productos { get; set; }
        public int id_Ingredientes { get; set; }
        public float Porcion { get; set; }
        public Nullable<int> FK_UnidadAlimenticia { get; set; }
    
        public virtual Cat_Producto Cat_Producto { get; set; }
        public virtual UnidadAlimenticia UnidadAlimenticia { get; set; }
    }
}
