//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasSSyPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Platillos = new HashSet<Platillos>();
        }
    
        public int id_Menu { get; set; }
        public string Tipo { get; set; }
        public int Numero { get; set; }
        public string Descripcion { get; set; }
        public string fecha { get; set; }
    
        public virtual ICollection<Platillos> Platillos { get; set; }
    }
}
