//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistasSSyPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platillos
    {
        public Platillos()
        {
            this.UnidadAlimenticia = new HashSet<UnidadAlimenticia>();
        }
    
        public string Nombre { get; set; }
        public int id_platillo { get; set; }
        public int FK_Menu { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<UnidadAlimenticia> UnidadAlimenticia { get; set; }
    }
}
