//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Marcas
    {
        public Cat_Marcas()
        {
            this.Cat_Productos = new HashSet<Cat_Productos>();
        }
    
        public int id_Marca { get; set; }
        public string Nombre { get; set; }
        public byte[] activo { get; set; }
    
        public virtual ICollection<Cat_Productos> Cat_Productos { get; set; }
    }
}
