//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Productos
    {
        public Cat_Productos()
        {
            this.Ingredientes = new HashSet<Ingredientes>();
            this.Tbl_Inventario = new HashSet<Tbl_Inventario>();
        }
    
        public int id_Producto { get; set; }
        public int id_UnidadesdeMedida { get; set; }
        public int id_Marca { get; set; }
        public int id_Modelo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Nombre { get; set; }
    
        public virtual Cat_Marcas Cat_Marcas { get; set; }
        public virtual Cat_Modelos Cat_Modelos { get; set; }
        public virtual Unidades_de__medidas Unidades_de__medidas { get; set; }
        public virtual ICollection<Ingredientes> Ingredientes { get; set; }
        public virtual ICollection<Tbl_Inventario> Tbl_Inventario { get; set; }
    }
}
