//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporacion
    {
        public Corporacion()
        {
            this.Almacen = new HashSet<Almacen>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id_Corporacion { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
