//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes
    {
        public Ingredientes()
        {
            this.Platillos = new HashSet<Platillos>();
        }
    
        public int id_Producto { get; set; }
        public int id_Ingrediente { get; set; }
        public float Porcion { get; set; }
        public int id_Unidad_de_Medida { get; set; }
    
        public virtual Cat_Productos Cat_Productos { get; set; }
        public virtual Unidades_Alimenticias Unidades_Alimenticias { get; set; }
        public virtual Unidades_de__medidas Unidades_de__medidas { get; set; }
        public virtual ICollection<Platillos> Platillos { get; set; }
    }
}
