//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SecretariaEntities : DbContext
    {
        public SecretariaEntities()
            : base("name=SecretariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Almacen> Almacen { get; set; }
        public DbSet<Areas> Areas { get; set; }
        public DbSet<Cat_Marcas> Cat_Marcas { get; set; }
        public DbSet<Cat_Modelos> Cat_Modelos { get; set; }
        public DbSet<Cat_Productos> Cat_Productos { get; set; }
        public DbSet<Corporacion> Corporacion { get; set; }
        public DbSet<Ingredientes> Ingredientes { get; set; }
        public DbSet<Menus> Menus { get; set; }
        public DbSet<Platillos> Platillos { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tbl_Inventario> Tbl_Inventario { get; set; }
        public DbSet<Unidades_Alimenticias> Unidades_Alimenticias { get; set; }
        public DbSet<Unidades_de__medidas> Unidades_de__medidas { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int Agregar_U_M(string u_M)
        {
            var u_MParameter = u_M != null ?
                new ObjectParameter("U_M", u_M) :
                new ObjectParameter("U_M", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Agregar_U_M", u_MParameter);
        }
    }
}
