//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inventario
    {
        public int id_Inventario { get; set; }
        public int id_Producto { get; set; }
        public int id_Almacen { get; set; }
        public string Existencia { get; set; }
        public int Stock_Minimo { get; set; }
        public int Stock_Maximo { get; set; }
    
        public virtual Almacen Almacen { get; set; }
        public virtual Cat_Productos Cat_Productos { get; set; }
    }
}
