//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades_Alimenticias
    {
        public Unidades_Alimenticias()
        {
            this.Ingredientes = new HashSet<Ingredientes>();
        }
    
        public int Id_Unidad_Alimenticia { get; set; }
        public int Cantidad_Personas { get; set; }
        public float Porcion { get; set; }
        public int id_Unidad_de_Medida { get; set; }
        public int id_Ingrediente { get; set; }
    
        public virtual ICollection<Ingredientes> Ingredientes { get; set; }
        public virtual Unidades_de__medidas Unidades_de__medidas { get; set; }
    }
}
